import { Inter, Quintessential} from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";



const inter = Inter({ subsets: ["latin"] });
const quintessential = Quintessential({ subsets: ["latin"], weight: ["400"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={quintessential.className}>
        <Navbar />
        {children}</body>
    </html>
  );
}
